version: "3.8"

services:
  nginx:
    build: 
      context: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - dragon
    networks:
      - app_network

  fastapi:
    build: ./docker/voice
    ports:
      - "8080:8080"
    networks:
      - app_network

  dragon:
    build: .docker/dragon
    ports:
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
